@baseUrl = http://127.0.0.1:3333

# @name create_account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
    "name": "Ismael Soares Doria",
    "email": "ismaeldoria@gmail.com",
    "password": "123456"
}

###

# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
    "email": "ismaeldoria@gmail.com",
    "password": "123456"
}

###
# @name create_question
POST {{baseUrl}}/questions
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJmYWRkZjcyMC00ZDEwLTQyMzAtOWFmMy1iYjQyOTA4YjZjMGIiLCJpYXQiOjE3MTQwNTkzMzF9.CfODQBpO3EDnE_frnLeF0ca80j8pFUncHH1sSJ7OFv84KvKn-HgtPBd5Md0u_mYoZs9yGQY8whBtUsTA3c3J3XeG8q08AMNR5nr3pMJTD4wTcHo9X13Bd__SbrU1aTYZN2yGvMjVlTu2L-j6oEmfpEIDs9rRVLnEGQPSeAe2OAqCXWSS-tLyFACq7DUrdPx0JXNkBWXTTOpipNoXoX4mlFFbcocwFYh0Yi7ohuv8wHOPoAkoD96Y8_JMeVU5E0elyX1-Kh2rElGrfVXPBWLHokFGF1rzoBn3TvNynDKftZLe1Tffp65gB8jbfcONHtPJTb1pS8_olXsda54nvJipgw
###
